# 线上配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyBI?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: self
    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 50MB
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: LWY-0212lwy
  # rabbitmq配置
  rabbitmq:
    port: 5672
    host: localhost
    username: lily
    password: 12345678
    listener:
      simple:
        # ACK模式(默认为auto)
        acknowledge-mode: auto
        # 开启重试
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
