# 公共配置文件
spring:
  application:
    name: easyBI
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/easyBI?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: self
#    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
#    host: 192.168.70.1
    port: 6379
    timeout: 5000
#    # redisson
#    redisson:
#      address: redis://192.169.70.129:6379
#      password:
#      timeout: 5000
#      database: 0
# rabbitmq配置
#  rabbitmq:
#    port: 5672
#    host: localhost
#    username: guest
#    password: guest
#    listener:
#      simple:
#        # ACK模式(默认为auto)
#        acknowledge-mode: auto
#        # 开启重试
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# ai接口相关
  # 讯飞星火配置
#xunfei:
#  client:
#    appid: caa08a16
#    apiSecret: M2U2NWM3ODM0MDUzNmU0MTk5MzU4YjYx
#    apiKey: 2361b34bd4db0a07e136d695b88c9b3e

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lilyVia.springbootinit.controller
